In [1]:
import pandas as pd

import glob

path = r'C:\Users\Salma\Downloads\Arabic_Preprocissing_data-main\Arabic_Preprocissing_data-main\RenameDataset' # use your path

all_files = glob.glob(path + "/*.csv")

li = []

for filename in all_files:

    df = pd.read_csv(filename, index_col=None, header=0)

    li.append(df)

data = pd.concat(li, axis=0, ignore_index=True)

In [2]:
data.head()

   Unnamed: 0                              Arabic_Tweets_Cleaned
0           0  اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر ا...
1           1  بعد الله حرام تجي تلقي واقف اشاره عرض متعدي نا...
2           2                             لمس يد مرة واضح جد حكم
3           3                            خصوص هاتريك عمر راح صار
4           4                     الله أجبر كسر رجع أدهم قبل بكر

In [3]:
label = pd.read_csv(r'C:\Users\Salma\Downloads\Arabic_Preprocissing_data-main\Arabic_Preprocissing_data-main\Labels.csv')

In [4]:
label.head()

   Unnamed: 0  Unnamed: 0.1     label
0           0             0       MSA
1           1             1       MSA
2           2             2  DIAL_LEV
3           3             3  DIAL_LEV
4           4             4  DIAL_GLF

In [5]:
label = label.drop(['Unnamed: 0.1'], axis = 1)

In [6]:
label.head()

   Unnamed: 0     label
0           0       MSA
1           1       MSA
2           2  DIAL_LEV
3           3  DIAL_LEV
4           4  DIAL_GLF

In [7]:
label.shape

(30004, 2)

In [8]:
data.shape

(30000, 2)

In [10]:
tweets = pd.merge(data, label, on=["Unnamed: 0"])

In [12]:
tweets.head(50)

    Unnamed: 0                              Arabic_Tweets_Cleaned     label
0            0  اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر ا...       MSA
1            0  بركه زار خدم مدنيه زار تربيه تعليم خريج خريج خ...       MSA
2            0                                                شكر       MSA
3            0  مبرووك لكن خلي صاحب مركز رابع عشر لعب صاحب مرك...       MSA
4            0  راح وصل ماء ابدا لو حطو ماسور خمسون انش لانهاش...       MSA
5            1  بعد الله حرام تجي تلقي واقف اشاره عرض متعدي نا...       MSA
6            1                                            شرط خدم       MSA
7            1  توفيق زعيم مشكوور شبيه ريح ومشكوور خالد بلط جد...       MSA
8            1                                     عشان مقيم أيقظ       MSA
9            1  موسم غض نظر فوز خساره هناك انتصار مصاحب اخطاء ...       MSA
10           2                             لمس يد مرة واضح جد حكم  DIAL_LEV
11           2                                            شرط خدم  DIAL_LEV
12           2                                يش تكلمتوا المباراه  DIAL_LEV
13           2                          علاقة بين السعوديه امريكا  DIAL_LEV
14           2  الله حراام جزيره خسر لان لاعب نصر اغلب مزور بس...  DIAL_LEV
15           3                            خصوص هاتريك عمر راح صار  DIAL_LEV
16           3                                      توفيق صلى شاء  DIAL_LEV
17           3                            تري فزع نهايه يبي مقابل  DIAL_LEV
18           3                                      لكن لم يعجيني  DIAL_LEV
19           3              غريب رقضكوا موش طايق سمع اسم نادي ابو  DIAL_LEV
20           4                     الله أجبر كسر رجع أدهم قبل بكر  DIAL_GLF
21           4  غد مارد اخضر عزف سمفيونيه وحداتيه انغام جماهيي...  DIAL_GLF
22           4                                           اوج جميع  DIAL_GLF
23           4  فيصلي اثبت مبار امس لا استحق دوري هدي شاب اردن...  DIAL_GLF
24           4                       ياليتني حضي اصير رجل اجل كتب  DIAL_GLF
25           5  تعدد اسباب موت حد عمر وث اوراق شجرة لبد سقط يا...       MSA
26           5  تخيل مع ترتيب رابع عشر عالم احصي مع كم وجد ناد...       MSA
27           5    سءال هل صاحب شخصيه ندره حصول زمن هل انسان طبيعي       MSA
28           5  لماذا منطقة جنوبيه محروم سك حديد ثم وجود سك حد...       MSA
29           5  عنى الله عند سءءال قال ماتمشي اموري امور اهل ب...       MSA
30           6                                   الله يزرقكم واسع       MSA
31           6  لو مثل مابتقولو محمود لعب صح انسان نجاح دار لا...       MSA
32           6  تدخين حرام لاتدخن ادعو منع تدخين ارجوك لا دخن ...       MSA
33           6        فتش اسراءيل هيلوكوبتر عمل معاهدة حماي ايران       MSA
34           6  عنى الله عند سءءال قال ماتمشي اموري امور اهل ب...       MSA
35           7                        ملفت مبهر ما احتاج تامل سبع       MSA
36           7  طب يش بترفعو سعر دخان خمر اشياء حرام ولي ناس مدمن       MSA
37           7                             فرحة داخل ابن ماسك شها       MSA
38           7                                           الله قام       MSA
39           7                                            وش حلاق       MSA
40           8                                       سلام على رحم       MSA
41           8  عربي فصيح لايصح الا صحيح كاس وحدة لان لن ذهب م...       MSA
42           8                            لا مستر برادعي اقصد جلب       MSA
43           8                          غز حاج ابطال مو حاج اغاني       MSA
44           8  يااخ عدل لا تطمءن من حول من هم عبيد لاي محافظ ...       MSA
45           9       اغلب تعليق سابق اقل وصف انها سخيف وبه افتراء       MSA
46           9              اتوقع اشتغل نظام راح ارتفع ميزانيه 10       MSA
47           9               اما الان حدث لا حرج الان خرج على موض       MSA
48           9                            ناس فرح عارم شعب نصراوي       MSA
49           9                                          مين لي ان       MSA

In [13]:
tweets.shape

(30000, 3)

In [14]:
tweets.dropna(inplace=True)

In [15]:
tweets.reset_index(drop= True)

       Unnamed: 0                              Arabic_Tweets_Cleaned label
0               0  اضافه قيام معلمو جيزه ذهاب جريد سابع نشر خبر ا...   MSA
1               0  بركه زار خدم مدنيه زار تربيه تعليم خريج خريج خ...   MSA
2               0                                                شكر   MSA
3               0  مبرووك لكن خلي صاحب مركز رابع عشر لعب صاحب مرك...   MSA
4               0  راح وصل ماء ابدا لو حطو ماسور خمسون انش لانهاش...   MSA
...           ...                                                ...   ...
29866        5999                             صاير ثقيل دم معكوس راح   MSA
29867        5999  انو مجتمع اردني اكثر مجتمع عربيه تعليم وعي ثقا...   MSA
29868        5999              صانع بطاله هم عامل وافده متي تنفس بلد   MSA
29869        5999  اما رقم ابراهيم مصري تحدث قاعد امريكي جزاءر مك...   MSA
29870        5999                              امطار ماشاء الله اكثر   MSA

[29871 rows x 3 columns]

In [16]:
tweets.to_csv(r'C:\Users\Salma\Downloads\Arabic_Preprocissing_data-main\Arabic_Preprocissing_data-main\FinishedDataset.csv')